USE AgnosticReservation;
GO

SET NOCOUNT ON;

DECLARE @Now DATETIME2(7) = SYSUTCDATETIME();

DECLARE @TenantDomains TABLE (Domain NVARCHAR(200));
INSERT INTO @TenantDomains (Domain)
VALUES
    ('beauty.agnostic.test'),
    ('auto.agnostic.test'),
    ('fitness.agnostic.test'),
    ('edu.agnostic.test'),
    ('pet.agnostic.test');

DECLARE @LocalizationKeys TABLE ([Key] NVARCHAR(200), Description NVARCHAR(500));
INSERT INTO @LocalizationKeys ([Key], Description)
VALUES
    ('app.header.title', N'Uygulama başlık metni'),
    ('app.header.subtitle', N'Uygulama alt başlık metni'),
    ('localization.admin.title', N'Çoklu dil ekranı başlığı'),
    ('localization.admin.description', N'Çoklu dil ekranı açıklaması'),
    ('localization.admin.addButton', N'Çeviri ekle butonu'),
    ('localization.admin.keyLabel', N'Anahtar alan etiketi'),
    ('localization.admin.languageLabel', N'Dil alan etiketi'),
    ('localization.admin.valueLabel', N'Metin alan etiketi'),
    ('localization.admin.infoLabel', N'Açıklama alanı etiketi'),
    ('localization.admin.descriptionPlaceholder', N'Açıklama alanı ipucu'),
    ('localization.admin.tableDescription', N'Tablo açıklama başlığı'),
    ('localization.admin.emptyState', N'Kayıt bulunamadı mesajı'),
    ('localization.admin.toastSaved', N'Çeviri kaydetme bildirimi'),
    ('localization.admin.toastCleared', N'Önbellek temizleme bildirimi'),
    ('localization.admin.searchPlaceholder', N'Arama alanı ipucu'),
    ('localization.admin.validation', N'Zorunlu alan uyarısı'),
    ('localization.admin.loading', N'Yüklenme metni'),
    ('auth.signIn.title', N'Giriş ekranı başlık metni'),
    ('auth.signIn.tenantPlaceholder', N'Giriş ekranı tenant kimliği alanı ipucu'),
    ('auth.signIn.emailPlaceholder', N'Giriş ekranı e-posta alanı ipucu'),
    ('auth.signIn.passwordPlaceholder', N'Giriş ekranı şifre alanı ipucu'),
    ('auth.signIn.submit', N'Giriş ekranı buton metni'),
    ('auth.signIn.loading', N'Giriş işlemi yükleniyor metni'),
    ('auth.signIn.navigateToSignUp', N'Giriş ekranı kayıt yönlendirme metni'),
    ('auth.signIn.errorTitle', N'Giriş hata başlığı'),
    ('auth.signIn.errorDescription', N'Giriş hata açıklaması'),
    ('auth.signUp.title', N'Kayıt ekranı başlık metni'),
    ('auth.signUp.tenantPlaceholder', N'Kayıt ekranı tenant kimliği alanı ipucu'),
    ('auth.signUp.fullNamePlaceholder', N'Kayıt ekranı ad soyad alanı ipucu'),
    ('auth.signUp.emailPlaceholder', N'Kayıt ekranı e-posta alanı ipucu'),
    ('auth.signUp.passwordPlaceholder', N'Kayıt ekranı şifre alanı ipucu'),
    ('auth.signUp.themeLabel', N'Kayıt ekranı tema etiketi'),
    ('auth.signUp.themeLight', N'Kayıt ekranı açık tema seçeneği'),
    ('auth.signUp.themeDark', N'Kayıt ekranı koyu tema seçeneği'),
    ('auth.signUp.submit', N'Kayıt ekranı buton metni'),
    ('auth.signUp.loading', N'Kayıt işlemi yükleniyor metni'),
    ('auth.signUp.errorTitle', N'Kayıt hata başlığı'),
    ('auth.signUp.errorDescription', N'Kayıt hata açıklaması'),
    ('navigation.tab.dashboard', N'Mobil sekme dashboard etiketi'),
    ('navigation.tab.reservations', N'Mobil sekme rezervasyonlar etiketi'),
    ('navigation.tab.admin', N'Mobil sekme yönetim etiketi'),
    ('admin.theme.title', N'Mobil yönetim tema kartı başlığı'),
    ('admin.theme.darkModeLabel', N'Mobil yönetim karanlık mod etiketi'),
    ('admin.parameters.title', N'Mobil yönetim parametreler kartı başlığı'),
    ('admin.parameters.refresh', N'Mobil yönetim parametreler yenile butonu'),
    ('admin.parameters.loading', N'Mobil yönetim parametreler yenileme metni'),
    ('admin.cache.title', N'Mobil yönetim önbellek kartı başlığı'),
    ('admin.cache.invalidate', N'Mobil yönetim önbellek temizleme butonu'),
    ('dashboard.kpi.utilization', N'Mobil panel kullanım KPI etiketi'),
    ('dashboard.kpi.revenue', N'Mobil panel gelir KPI etiketi'),
    ('dashboard.quickBook.title', N'Mobil hızlı rezervasyon başlığı'),
    ('dashboard.utilizationChart.title', N'Mobil kullanım grafiği başlığı'),
    ('dashboard.utilizationChart.day.mon', N'Mobil kullanım grafiği pazartesi etiketi'),
    ('dashboard.utilizationChart.day.tue', N'Mobil kullanım grafiği salı etiketi'),
    ('dashboard.utilizationChart.day.wed', N'Mobil kullanım grafiği çarşamba etiketi'),
    ('dashboard.stockAlerts.title', N'Mobil stok uyarıları başlığı'),
    ('dashboard.stockAlerts.empty', N'Mobil stok uyarıları boş mesajı'),
    ('dashboard.payments.title', N'Mobil ödemeler başlığı'),
    ('dashboard.payments.pending', N'Mobil ödemeler beklemede metni'),
    ('dashboard.payments.failed', N'Mobil ödemeler başarısız metni'),
    ('dashboard.meta.roleWidgets', N'Mobil panel rol widget sayısı metni'),
    ('resources.roomA', N'Örnek kaynak oda A adı'),
    ('resources.roomB', N'Örnek kaynak oda B adı'),
    ('resources.roomC', N'Örnek kaynak oda C adı'),
    ('events.discovery', N'Örnek etkinlik keşif adı'),
    ('events.demo', N'Örnek etkinlik demo adı'),
    ('events.standup', N'Örnek etkinlik standup adı'),
    ('events.planning', N'Örnek etkinlik planlama adı'),
    ('inventory.item.welcomeKits', N'Örnek stok öğesi hoş geldin paketleri adı');

DECLARE @Translations TABLE ([Key] NVARCHAR(200), Language NVARCHAR(10), [Value] NVARCHAR(1024));
INSERT INTO @Translations ([Key], Language, [Value])
VALUES
    ('app.header.title', 'tr-TR', N'Agnostic Rezervasyon Paneli'),
    ('app.header.title', 'en-US', N'Agnostic Reservation Console'),
    ('app.header.title', 'en-GB', N'Agnostic Reservation Console'),
    ('app.header.title', 'de-DE', N'Agnostic Reservierungs-Konsole'),
    ('app.header.subtitle', 'tr-TR', N'Tenant bazlı yönetim ve çeviri kontrolü'),
    ('app.header.subtitle', 'en-US', N'Tenant-specific management and localization control'),
    ('app.header.subtitle', 'en-GB', N'Tenant-specific management and localisation control'),
    ('app.header.subtitle', 'de-DE', N'Mandantenspezifische Verwaltung und Übersetzungssteuerung'),
    ('localization.admin.title', 'tr-TR', N'Çoklu Dil Yönetimi'),
    ('localization.admin.title', 'en-US', N'Multi-language Management'),
    ('localization.admin.title', 'en-GB', N'Multi-language Management'),
    ('localization.admin.title', 'de-DE', N'Mehrsprachenverwaltung'),
    ('localization.admin.description', 'tr-TR', N'Anahtar bazında farklı diller için metinleri buradan güncelleyebilirsiniz.'),
    ('localization.admin.description', 'en-US', N'Update every language variant for a key from this screen.'),
    ('localization.admin.description', 'en-GB', N'Update every language variant for a key from this screen.'),
    ('localization.admin.description', 'de-DE', N'Aktualisieren Sie hier die Texte pro Sprache und Schlüssel.'),
    ('localization.admin.addButton', 'tr-TR', N'Yeni çeviri ekle'),
    ('localization.admin.addButton', 'en-US', N'Add translation'),
    ('localization.admin.addButton', 'en-GB', N'Add translation'),
    ('localization.admin.addButton', 'de-DE', N'Übersetzung hinzufügen'),
    ('localization.admin.keyLabel', 'tr-TR', N'Anahtar'),
    ('localization.admin.keyLabel', 'en-US', N'Key'),
    ('localization.admin.keyLabel', 'en-GB', N'Key'),
    ('localization.admin.keyLabel', 'de-DE', N'Schlüssel'),
    ('localization.admin.languageLabel', 'tr-TR', N'Dil'),
    ('localization.admin.languageLabel', 'en-US', N'Language'),
    ('localization.admin.languageLabel', 'en-GB', N'Language'),
    ('localization.admin.languageLabel', 'de-DE', N'Sprache'),
    ('localization.admin.valueLabel', 'tr-TR', N'Metin'),
    ('localization.admin.valueLabel', 'en-US', N'Text'),
    ('localization.admin.valueLabel', 'en-GB', N'Text'),
    ('localization.admin.valueLabel', 'de-DE', N'Text'),
    ('localization.admin.infoLabel', 'tr-TR', N'Bilgi'),
    ('localization.admin.infoLabel', 'en-US', N'Details'),
    ('localization.admin.infoLabel', 'en-GB', N'Details'),
    ('localization.admin.infoLabel', 'de-DE', N'Hinweis'),
    ('localization.admin.descriptionPlaceholder', 'tr-TR', N'İsteğe bağlı açıklama'),
    ('localization.admin.descriptionPlaceholder', 'en-US', N'Optional description'),
    ('localization.admin.descriptionPlaceholder', 'en-GB', N'Optional description'),
    ('localization.admin.descriptionPlaceholder', 'de-DE', N'Optionale Beschreibung'),
    ('localization.admin.tableDescription', 'tr-TR', N'Açıklama'),
    ('localization.admin.tableDescription', 'en-US', N'Description'),
    ('localization.admin.tableDescription', 'en-GB', N'Description'),
    ('localization.admin.tableDescription', 'de-DE', N'Beschreibung'),
    ('localization.admin.emptyState', 'tr-TR', N'Henüz tanımlanmış bir çeviri bulunmuyor.'),
    ('localization.admin.emptyState', 'en-US', N'No translations defined yet.'),
    ('localization.admin.emptyState', 'en-GB', N'No translations defined yet.'),
    ('localization.admin.emptyState', 'de-DE', N'Noch keine Übersetzungen vorhanden.'),
    ('localization.admin.toastSaved', 'tr-TR', N'Çeviri kaydedildi.'),
    ('localization.admin.toastSaved', 'en-US', N'Translation saved.'),
    ('localization.admin.toastSaved', 'en-GB', N'Translation saved.'),
    ('localization.admin.toastSaved', 'de-DE', N'Übersetzung gespeichert.'),
    ('localization.admin.toastCleared', 'tr-TR', N'Çeviri önbelleği temizlendi.'),
    ('localization.admin.toastCleared', 'en-US', N'Localization cache cleared.'),
    ('localization.admin.toastCleared', 'en-GB', N'Localization cache cleared.'),
    ('localization.admin.toastCleared', 'de-DE', N'Übersetzungs-Cache geleert.'),
    ('localization.admin.searchPlaceholder', 'tr-TR', N'Anahtar ara...'),
    ('localization.admin.searchPlaceholder', 'en-US', N'Search key...'),
    ('localization.admin.searchPlaceholder', 'en-GB', N'Search key...'),
    ('localization.admin.searchPlaceholder', 'de-DE', N'Schlüssel suchen...'),
    ('localization.admin.validation', 'tr-TR', N'Anahtar, dil ve metin alanları zorunludur.'),
    ('localization.admin.validation', 'en-US', N'Key, language and text fields are required.'),
    ('localization.admin.validation', 'en-GB', N'Key, language and text fields are required.'),
    ('localization.admin.validation', 'de-DE', N'Schlüssel, Sprache und Text sind Pflichtfelder.'),
    ('localization.admin.loading', 'tr-TR', N'Yükleniyor...'),
    ('localization.admin.loading', 'en-US', N'Loading...'),
    ('localization.admin.loading', 'en-GB', N'Loading...'),
    ('localization.admin.loading', 'de-DE', N'Wird geladen...'),
    ('auth.signIn.title', 'tr-TR', N'Tekrar hoş geldiniz'),
    ('auth.signIn.title', 'en-US', N'Welcome Back'),
    ('auth.signIn.title', 'en-GB', N'Welcome Back'),
    ('auth.signIn.title', 'de-DE', N'Willkommen zurück'),
    ('auth.signIn.tenantPlaceholder', 'tr-TR', N'Tenant kimliği'),
    ('auth.signIn.tenantPlaceholder', 'en-US', N'Tenant ID'),
    ('auth.signIn.tenantPlaceholder', 'en-GB', N'Tenant ID'),
    ('auth.signIn.tenantPlaceholder', 'de-DE', N'Mandanten-ID'),
    ('auth.signIn.emailPlaceholder', 'tr-TR', N'E-posta'),
    ('auth.signIn.emailPlaceholder', 'en-US', N'Email'),
    ('auth.signIn.emailPlaceholder', 'en-GB', N'Email'),
    ('auth.signIn.emailPlaceholder', 'de-DE', N'E-Mail'),
    ('auth.signIn.passwordPlaceholder', 'tr-TR', N'Şifre'),
    ('auth.signIn.passwordPlaceholder', 'en-US', N'Password'),
    ('auth.signIn.passwordPlaceholder', 'en-GB', N'Password'),
    ('auth.signIn.passwordPlaceholder', 'de-DE', N'Passwort'),
    ('auth.signIn.submit', 'tr-TR', N'Giriş yap'),
    ('auth.signIn.submit', 'en-US', N'Sign In'),
    ('auth.signIn.submit', 'en-GB', N'Sign In'),
    ('auth.signIn.submit', 'de-DE', N'Anmelden'),
    ('auth.signIn.loading', 'tr-TR', N'Giriş yapılıyor...'),
    ('auth.signIn.loading', 'en-US', N'Signing in...'),
    ('auth.signIn.loading', 'en-GB', N'Signing in...'),
    ('auth.signIn.loading', 'de-DE', N'Anmeldung läuft...'),
    ('auth.signIn.navigateToSignUp', 'tr-TR', N'Hesabın yok mu? Kaydol'),
    ('auth.signIn.navigateToSignUp', 'en-US', N'Need an account? Sign up'),
    ('auth.signIn.navigateToSignUp', 'en-GB', N'Need an account? Sign up'),
    ('auth.signIn.navigateToSignUp', 'de-DE', N'Noch kein Konto? Registrieren'),
    ('auth.signIn.errorTitle', 'tr-TR', N'Giriş başarısız'),
    ('auth.signIn.errorTitle', 'en-US', N'Sign in failed'),
    ('auth.signIn.errorTitle', 'en-GB', N'Sign in failed'),
    ('auth.signIn.errorTitle', 'de-DE', N'Anmeldung fehlgeschlagen'),
    ('auth.signIn.errorDescription', 'tr-TR', N'Lütfen bilgilerinizi kontrol edin'),
    ('auth.signIn.errorDescription', 'en-US', N'Please check your credentials'),
    ('auth.signIn.errorDescription', 'en-GB', N'Please check your credentials'),
    ('auth.signIn.errorDescription', 'de-DE', N'Bitte überprüfen Sie Ihre Zugangsdaten'),
    ('auth.signUp.title', 'tr-TR', N'Hesap oluştur'),
    ('auth.signUp.title', 'en-US', N'Create Account'),
    ('auth.signUp.title', 'en-GB', N'Create Account'),
    ('auth.signUp.title', 'de-DE', N'Konto erstellen'),
    ('auth.signUp.tenantPlaceholder', 'tr-TR', N'Tenant kimliği'),
    ('auth.signUp.tenantPlaceholder', 'en-US', N'Tenant ID'),
    ('auth.signUp.tenantPlaceholder', 'en-GB', N'Tenant ID'),
    ('auth.signUp.tenantPlaceholder', 'de-DE', N'Mandanten-ID'),
    ('auth.signUp.fullNamePlaceholder', 'tr-TR', N'Ad Soyad'),
    ('auth.signUp.fullNamePlaceholder', 'en-US', N'Full Name'),
    ('auth.signUp.fullNamePlaceholder', 'en-GB', N'Full Name'),
    ('auth.signUp.fullNamePlaceholder', 'de-DE', N'Vollständiger Name'),
    ('auth.signUp.emailPlaceholder', 'tr-TR', N'E-posta'),
    ('auth.signUp.emailPlaceholder', 'en-US', N'Email'),
    ('auth.signUp.emailPlaceholder', 'en-GB', N'Email'),
    ('auth.signUp.emailPlaceholder', 'de-DE', N'E-Mail'),
    ('auth.signUp.passwordPlaceholder', 'tr-TR', N'Şifre'),
    ('auth.signUp.passwordPlaceholder', 'en-US', N'Password'),
    ('auth.signUp.passwordPlaceholder', 'en-GB', N'Password'),
    ('auth.signUp.passwordPlaceholder', 'de-DE', N'Passwort'),
    ('auth.signUp.themeLabel', 'tr-TR', N'Tema'),
    ('auth.signUp.themeLabel', 'en-US', N'Theme'),
    ('auth.signUp.themeLabel', 'en-GB', N'Theme'),
    ('auth.signUp.themeLabel', 'de-DE', N'Thema'),
    ('auth.signUp.themeLight', 'tr-TR', N'Açık'),
    ('auth.signUp.themeLight', 'en-US', N'Light'),
    ('auth.signUp.themeLight', 'en-GB', N'Light'),
    ('auth.signUp.themeLight', 'de-DE', N'Hell'),
    ('auth.signUp.themeDark', 'tr-TR', N'Koyu'),
    ('auth.signUp.themeDark', 'en-US', N'Dark'),
    ('auth.signUp.themeDark', 'en-GB', N'Dark'),
    ('auth.signUp.themeDark', 'de-DE', N'Dunkel'),
    ('auth.signUp.submit', 'tr-TR', N'Kaydol'),
    ('auth.signUp.submit', 'en-US', N'Sign Up'),
    ('auth.signUp.submit', 'en-GB', N'Sign Up'),
    ('auth.signUp.submit', 'de-DE', N'Registrieren'),
    ('auth.signUp.loading', 'tr-TR', N'Kayıt yapılıyor...'),
    ('auth.signUp.loading', 'en-US', N'Signing up...'),
    ('auth.signUp.loading', 'en-GB', N'Signing up...'),
    ('auth.signUp.loading', 'de-DE', N'Registrierung läuft...'),
    ('auth.signUp.errorTitle', 'tr-TR', N'Kayıt başarısız'),
    ('auth.signUp.errorTitle', 'en-US', N'Sign up failed'),
    ('auth.signUp.errorTitle', 'en-GB', N'Sign up failed'),
    ('auth.signUp.errorTitle', 'de-DE', N'Registrierung fehlgeschlagen'),
    ('auth.signUp.errorDescription', 'tr-TR', N'Lütfen bilgilerinizi gözden geçirin'),
    ('auth.signUp.errorDescription', 'en-US', N'Please review your details'),
    ('auth.signUp.errorDescription', 'en-GB', N'Please review your details'),
    ('auth.signUp.errorDescription', 'de-DE', N'Bitte prüfen Sie Ihre Angaben'),
    ('navigation.tab.dashboard', 'tr-TR', N'Panel'),
    ('navigation.tab.dashboard', 'en-US', N'Dashboard'),
    ('navigation.tab.dashboard', 'en-GB', N'Dashboard'),
    ('navigation.tab.dashboard', 'de-DE', N'Übersicht'),
    ('navigation.tab.reservations', 'tr-TR', N'Rezervasyonlar'),
    ('navigation.tab.reservations', 'en-US', N'Reservations'),
    ('navigation.tab.reservations', 'en-GB', N'Reservations'),
    ('navigation.tab.reservations', 'de-DE', N'Reservierungen'),
    ('navigation.tab.admin', 'tr-TR', N'Yönetim'),
    ('navigation.tab.admin', 'en-US', N'Admin'),
    ('navigation.tab.admin', 'en-GB', N'Admin'),
    ('navigation.tab.admin', 'de-DE', N'Verwaltung'),
    ('admin.theme.title', 'tr-TR', N'Tema'),
    ('admin.theme.title', 'en-US', N'Theme'),
    ('admin.theme.title', 'en-GB', N'Theme'),
    ('admin.theme.title', 'de-DE', N'Thema'),
    ('admin.theme.darkModeLabel', 'tr-TR', N'Karanlık mod'),
    ('admin.theme.darkModeLabel', 'en-US', N'Dark mode'),
    ('admin.theme.darkModeLabel', 'en-GB', N'Dark mode'),
    ('admin.theme.darkModeLabel', 'de-DE', N'Dunkelmodus'),
    ('admin.parameters.title', 'tr-TR', N'Parametreler'),
    ('admin.parameters.title', 'en-US', N'Parameters'),
    ('admin.parameters.title', 'en-GB', N'Parameters'),
    ('admin.parameters.title', 'de-DE', N'Parameter'),
    ('admin.parameters.refresh', 'tr-TR', N'Yenile'),
    ('admin.parameters.refresh', 'en-US', N'Refresh'),
    ('admin.parameters.refresh', 'en-GB', N'Refresh'),
    ('admin.parameters.refresh', 'de-DE', N'Aktualisieren'),
    ('admin.parameters.loading', 'tr-TR', N'Yenileniyor...'),
    ('admin.parameters.loading', 'en-US', N'Refreshing...'),
    ('admin.parameters.loading', 'en-GB', N'Refreshing...'),
    ('admin.parameters.loading', 'de-DE', N'Aktualisierung...'),
    ('admin.cache.title', 'tr-TR', N'Önbellek'),
    ('admin.cache.title', 'en-US', N'Cache'),
    ('admin.cache.title', 'en-GB', N'Cache'),
    ('admin.cache.title', 'de-DE', N'Zwischenspeicher'),
    ('admin.cache.invalidate', 'tr-TR', N'Tenant önbelleğini temizle'),
    ('admin.cache.invalidate', 'en-US', N'Invalidate tenant cache'),
    ('admin.cache.invalidate', 'en-GB', N'Invalidate tenant cache'),
    ('admin.cache.invalidate', 'de-DE', N'Tenant-Zwischenspeicher leeren'),
    ('dashboard.kpi.utilization', 'tr-TR', N'Kullanım'),
    ('dashboard.kpi.utilization', 'en-US', N'Utilization'),
    ('dashboard.kpi.utilization', 'en-GB', N'Utilisation'),
    ('dashboard.kpi.utilization', 'de-DE', N'Auslastung'),
    ('dashboard.kpi.revenue', 'tr-TR', N'Gelir'),
    ('dashboard.kpi.revenue', 'en-US', N'Revenue'),
    ('dashboard.kpi.revenue', 'en-GB', N'Revenue'),
    ('dashboard.kpi.revenue', 'de-DE', N'Umsatz'),
    ('dashboard.quickBook.title', 'tr-TR', N'Hızlı rezervasyon'),
    ('dashboard.quickBook.title', 'en-US', N'Quick Book'),
    ('dashboard.quickBook.title', 'en-GB', N'Quick Book'),
    ('dashboard.quickBook.title', 'de-DE', N'Schnellbuchung'),
    ('dashboard.utilizationChart.title', 'tr-TR', N'Kullanım grafiği'),
    ('dashboard.utilizationChart.title', 'en-US', N'Utilization'),
    ('dashboard.utilizationChart.title', 'en-GB', N'Utilisation'),
    ('dashboard.utilizationChart.title', 'de-DE', N'Auslastung'),
    ('dashboard.utilizationChart.day.mon', 'tr-TR', N'Pzt'),
    ('dashboard.utilizationChart.day.mon', 'en-US', N'Mon'),
    ('dashboard.utilizationChart.day.mon', 'en-GB', N'Mon'),
    ('dashboard.utilizationChart.day.mon', 'de-DE', N'Mo'),
    ('dashboard.utilizationChart.day.tue', 'tr-TR', N'Sal'),
    ('dashboard.utilizationChart.day.tue', 'en-US', N'Tue'),
    ('dashboard.utilizationChart.day.tue', 'en-GB', N'Tue'),
    ('dashboard.utilizationChart.day.tue', 'de-DE', N'Di'),
    ('dashboard.utilizationChart.day.wed', 'tr-TR', N'Çar'),
    ('dashboard.utilizationChart.day.wed', 'en-US', N'Wed'),
    ('dashboard.utilizationChart.day.wed', 'en-GB', N'Wed'),
    ('dashboard.utilizationChart.day.wed', 'de-DE', N'Mi'),
    ('dashboard.stockAlerts.title', 'tr-TR', N'Stok uyarıları'),
    ('dashboard.stockAlerts.title', 'en-US', N'Stock Alerts'),
    ('dashboard.stockAlerts.title', 'en-GB', N'Stock Alerts'),
    ('dashboard.stockAlerts.title', 'de-DE', N'Bestandswarnungen'),
    ('dashboard.stockAlerts.empty', 'tr-TR', N'Uyarı yok 🎉'),
    ('dashboard.stockAlerts.empty', 'en-US', N'No alerts 🎉'),
    ('dashboard.stockAlerts.empty', 'en-GB', N'No alerts 🎉'),
    ('dashboard.stockAlerts.empty', 'de-DE', N'Keine Warnungen 🎉'),
    ('dashboard.payments.title', 'tr-TR', N'Ödemeler'),
    ('dashboard.payments.title', 'en-US', N'Payments'),
    ('dashboard.payments.title', 'en-GB', N'Payments'),
    ('dashboard.payments.title', 'de-DE', N'Zahlungen'),
    ('dashboard.payments.pending', 'tr-TR', N'{{count}} beklemede'),
    ('dashboard.payments.pending', 'en-US', N'{{count}} pending'),
    ('dashboard.payments.pending', 'en-GB', N'{{count}} pending'),
    ('dashboard.payments.pending', 'de-DE', N'{{count}} offen'),
    ('dashboard.payments.failed', 'tr-TR', N'{{count}} başarısız'),
    ('dashboard.payments.failed', 'en-US', N'{{count}} failed'),
    ('dashboard.payments.failed', 'en-GB', N'{{count}} failed'),
    ('dashboard.payments.failed', 'de-DE', N'{{count}} fehlgeschlagen'),
    ('dashboard.meta.roleWidgets', 'tr-TR', N'Rol bileşenleri: {{count}}'),
    ('dashboard.meta.roleWidgets', 'en-US', N'Role widgets: {{count}}'),
    ('dashboard.meta.roleWidgets', 'en-GB', N'Role widgets: {{count}}'),
    ('dashboard.meta.roleWidgets', 'de-DE', N'Rollen-Widgets: {{count}}'),
    ('resources.roomA', 'tr-TR', N'Oda A'),
    ('resources.roomA', 'en-US', N'Room A'),
    ('resources.roomA', 'en-GB', N'Room A'),
    ('resources.roomA', 'de-DE', N'Raum A'),
    ('resources.roomB', 'tr-TR', N'Oda B'),
    ('resources.roomB', 'en-US', N'Room B'),
    ('resources.roomB', 'en-GB', N'Room B'),
    ('resources.roomB', 'de-DE', N'Raum B'),
    ('resources.roomC', 'tr-TR', N'Oda C'),
    ('resources.roomC', 'en-US', N'Room C'),
    ('resources.roomC', 'en-GB', N'Room C'),
    ('resources.roomC', 'de-DE', N'Raum C'),
    ('events.discovery', 'tr-TR', N'Keşif'),
    ('events.discovery', 'en-US', N'Discovery'),
    ('events.discovery', 'en-GB', N'Discovery'),
    ('events.discovery', 'de-DE', N'Einführung'),
    ('events.demo', 'tr-TR', N'Demo'),
    ('events.demo', 'en-US', N'Demo'),
    ('events.demo', 'en-GB', N'Demo'),
    ('events.demo', 'de-DE', N'Demo'),
    ('events.standup', 'tr-TR', N'Standup'),
    ('events.standup', 'en-US', N'Standup'),
    ('events.standup', 'en-GB', N'Standup'),
    ('events.standup', 'de-DE', N'Standup'),
    ('events.planning', 'tr-TR', N'Planlama'),
    ('events.planning', 'en-US', N'Planning'),
    ('events.planning', 'en-GB', N'Planning'),
    ('events.planning', 'de-DE', N'Planung'),
    ('inventory.item.welcomeKits', 'tr-TR', N'Hoş geldin paketleri'),
    ('inventory.item.welcomeKits', 'en-US', N'Welcome Kits'),
    ('inventory.item.welcomeKits', 'en-GB', N'Welcome Kits'),
    ('inventory.item.welcomeKits', 'de-DE', N'Willkommenspakete');

DECLARE @LocalizationSeed TABLE (TenantDomain NVARCHAR(200), [Key] NVARCHAR(200), Description NVARCHAR(500), Language NVARCHAR(10), [Value] NVARCHAR(1024));
INSERT INTO @LocalizationSeed (TenantDomain, [Key], Description, Language, [Value])
SELECT d.Domain, k.[Key], k.Description, t.Language, t.[Value]
FROM @TenantDomains d
JOIN @LocalizationKeys k ON 1 = 1
JOIN @Translations t ON t.[Key] = k.[Key];

DECLARE @Seed TABLE (TenantId UNIQUEIDENTIFIER, [Key] NVARCHAR(200), Description NVARCHAR(500), Language NVARCHAR(10), [Value] NVARCHAR(1024));
INSERT INTO @Seed (TenantId, [Key], Description, Language, [Value])
SELECT tn.Id, s.[Key], s.Description, s.Language, s.[Value]
FROM @LocalizationSeed s
JOIN dbo.Tenants tn ON tn.Domain = s.TenantDomain;

IF EXISTS (SELECT 1 FROM @Seed)
BEGIN
    ;WITH DistinctKeys AS (
        SELECT DISTINCT TenantId, [Key], Description
        FROM @Seed
    )
    MERGE dbo.LocalizationKeys AS target
    USING DistinctKeys AS source
        ON target.TenantId = source.TenantId AND target.[Key] = source.[Key]
    WHEN MATCHED THEN
        UPDATE SET Description = source.Description, UpdatedAt = @Now
    WHEN NOT MATCHED THEN
        INSERT (Id, TenantId, [Key], Description, CreatedAt)
        VALUES (NEWID(), source.TenantId, source.[Key], source.Description, @Now);

    ;WITH SourceTexts AS (
        SELECT s.TenantId, s.[Key], s.Language, s.[Value], k.Id AS LocalizationKeyId
        FROM @Seed s
        JOIN dbo.LocalizationKeys k ON k.TenantId = s.TenantId AND k.[Key] = s.[Key]
    )
    MERGE dbo.LocalizationTexts AS target
    USING SourceTexts AS source
        ON target.LocalizationKeyId = source.LocalizationKeyId AND target.Language = source.Language
    WHEN MATCHED THEN
        UPDATE SET [Value] = source.[Value], UpdatedAt = @Now
    WHEN NOT MATCHED THEN
        INSERT (Id, LocalizationKeyId, Language, [Value], CreatedAt)
        VALUES (NEWID(), source.LocalizationKeyId, source.Language, source.[Value], @Now);
END;
GO
