services:
  rootta:
    build:
      context: .
    depends_on:
      mongodb:
        condition: service_started
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: ""
      MongoLogging__IsEnabled: "true"
      MongoLogging__ConnectionString: mongodb://mongodb:27017
      MongoLogging__DatabaseName: agnostic_reservation_logs
      MongoLogging__GeneralCollectionName: general_request_logs
      MongoLogging__AccountingCollectionName: accounting_request_logs
      MongoLogging__Username: ${MONGODB_ROOT_USERNAME:-rootta_admin}
      MongoLogging__Password: ${MONGODB_ROOT_PASSWORD:-RoottaDev!123}
      MongoLogging__AuthenticationDatabase: admin
    ports:
      - "8080:8080"
    restart: unless-stopped

  mongodb:
    image: mongo:6.0
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ROOT_USERNAME:-rootta_admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD:-RoottaDev!123}
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

  mongo-express:
    image: mongo-express:1.0.0-18
    restart: unless-stopped
    depends_on:
      mongodb:
        condition: service_started
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_ROOT_USERNAME:-rootta_admin}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_ROOT_PASSWORD:-RoottaDev!123}
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_USERNAME:-rootta_dash}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASSWORD:-RoottaExpress!123}
    ports:
      - "8081:8081"

volumes:
  mongodb-data:
